### ISSUE TITLE
Generar datos ECOE no descarga fichero

### ISSUE THREAD

**Issue by sercutos** [openECOE/one-for-all#3]
Cuando estoy en la sección:
ecoe/1/results
y pulso sobre el botón descargar de la sección "Generar datos ECOE", no descarga el dichero.
Si hago la prueba en el servidor de pruebas si funciona: 
https://test-openecoe.umh.es/

**Comment by sercutos** [comment]
en base de datos encuentro esto: 
mysql> SELECT *  FROM job;
+--------------------------------------+-----------------------------------------------------+-------------------------------+---------+----------+---------------------+----------+------+
| id                                   | name                                                | description                   | user_id | complete | created             | finished | file |
+--------------------------------------+-----------------------------------------------------+-------------------------------+---------+----------+---------------------+----------+------+
| 311921bf-bd05-4b21-9bcb-3a79b8683eeb | app.jobs.statistics.generate_reports(id_ecoe=1)     | Generaci▒n de Notas ECOE = 21 |       1 |        0 | 2023-11-13 08:19:34 | NULL     | NULL |
| 3c74a4f1-d7eb-4a5d-986c-aa801ae95b0d | app.jobs.statistics.generate_reports(id_ecoe=1)     | Generaci▒n de Notas ECOE = 21 |       1 |        0 | 2023-11-07 19:53:29 | NULL     | NULL |
| 705c5208-cd81-4a80-94d6-59e6daa5d0e4 | app.jobs.statistics.generate_reports(id_ecoe=1)     | Generaci▒n de Notas ECOE = 21 |       1 |        0 | 2023-10-19 19:10:05 | NULL     | NULL |
| 7cb73a9e-83cb-4ce5-9d14-6a356d32f674 | app.jobs.statistics.export_csv(ecoe=1, identidad=1) | CSV_Asinc: ECOE = 21          |       1 |        0 | 2023-10-18 17:27:04 | NULL     | NULL |
| 86356c03-6270-4a8c-a7aa-572a556c8d60 | app.jobs.statistics.export_csv(ecoe=1, identidad=1) | CSV_Asinc: ECOE = 21          |       1 |        0 | 2023-10-19 19:47:21 | NULL     | NULL |
| 90c4b46f-e2df-4a0b-8e99-c8d6d549ce00 | app.jobs.statistics.export_csv(ecoe=1, identidad=1) | CSV_Asinc: ECOE = 21          |       1 |        0 | 2023-10-19 19:09:23 | NULL     | NULL |
| 9a9b8b6e-9808-4396-9452-47e54081065d | app.jobs.statistics.generate_reports(id_ecoe=1)     | Generaci▒n de Notas ECOE = 21 |       1 |        0 | 2023-11-13 08:28:46 | NULL     | NULL |
| e857008f-ae27-4178-b83e-7b84a344e9e6 | app.jobs.statistics.export_csv(ecoe=1, identidad=1) | CSV_Asinc: ECOE = 21          |       1 |        0 | 2023-10-19 19:10:11 | NULL     | NULL |
| f118f93c-5930-44c6-b666-a7e7bdad4550 | app.jobs.statistics.export_csv(ecoe=1, identidad=1) | CSV_Asinc: ECOE = 21          |       1 |        0 | 2023-10-18 17:26:31 | NULL     | NULL |
| f631df9d-62c4-45be-a85c-772f533f72b2 | app.jobs.statistics.generate_reports(id_ecoe=1)     | Generaci▒n de Notas ECOE = 21 |       1 |        0 | 2023-10-19 19:47:42 | NULL     | NULL |
+--------------------------------------+-----------------------------------------------------+-------------------------------+---------+----------+---------------------+----------+------+

**Comment by sercutos** [comment]
Si conecto al servidor de redis 172.19.0.2:6379> y ejecuto "monitor"
me arroja el siguiente error:

Error: You are trying to merge on object and int64 columns. 
If you wish to proceed you should use pd.concat\x94." "timeout" "300" "result_ttl" "500" "status" "finished"

Espero que os sirva

**Comment by sercutos** [comment]
He bajado la rama develop (tambien he probado con la master) pero al hacer las pruebas sigue dando el mismo error 404 not found
Comandos utilizados: 
```
~/docker$ uname -a
Linux openecoe2 6.5.0-15-generic #15~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Jan 12 18:54:30 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
git clone --branch develop https://github.com/openECOE/openECOE-deploy.git
cd docker/
sudo docker-compose up
```

**Comment by TuGeek** [comment]
Se lo pasó a los desarrolladores que han hecho los cambios para que lo
revisen.

**Comment by miguelaf0** [comment]
@sercutos Al hacer `docker image ls`, que tag y fecha de creación aparecen para las siguientes imágenes?:
- openecoe/api
- openecoe/webui
- openecoe/one-for-all

**Comment by sercutos** [comment]
@miguelaf0 


```
openecoe@openecoe2:~$ sudo docker image ls
REPOSITORY             TAG       IMAGE ID       CREATED         SIZE
openecoe/one-for-all   latest    f980e7d55bdd   7 minutes ago   833MB
mysql                  latest    31ebb0b19998   2 days ago      586MB
redis                  latest    9c893be668ac   6 weeks ago     116MB
```
----------------------------------------
```
openecoe@openecoe2:~$ sudo docker ps -a
CONTAINER ID   IMAGE                         COMMAND                  CREATED              STATUS                    PORTS                                   NAMES
14a208f6197b   openecoe/one-for-all:latest   "/docker-entrypoint.…"   About a minute ago   Up 28 seconds             0.0.0.0:8081->80/tcp, :::8081->80/tcp   docker_openecoe_1
9a1015ef6b89   mysql:latest                  "docker-entrypoint.s…"   About a minute ago   Up 58 seconds (healthy)   3306/tcp, 33060/tcp                     docker_db_1
30e6fc06ee89   redis:latest                  "docker-entrypoint.s…"   About a minute ago   Up 58 seconds             6379/tcp                                docker_redis_1
```
logs docker:

```
openecoe_1  | 14:51:51 Worker rq:worker:bacfbc3ddcd04820a26061a0171960ef: started, version 1.3.0
openecoe_1  | 14:51:51 *** Listening on openecoe_jobs...
openecoe_1  | 14:51:51 Cleaning registries for queue: openecoe_jobs
```
-------------------

```
14:56:14 openecoe_jobs: Job OK (d1a0df13-9a75-4f54-9da1-ef70de55bb6e)
14:56:14 Result is kept for 500 seconds
openecoe_1  | 192.168.153.1 - - [04/Jul/2024:14:57:08 +0000] "GET /backend/api/v1/jobs/d1a0df13-9a75-4f54-9da1-ef70de55bb6e HTTP/1.1" 200 262 "http://192.168.153.137:8081/ecoe/1/results" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "-"
openecoe_1  | 192.168.153.1 - - [04/Jul/2024:14:57:09 +0000] "GET /backend/api/v1/jobs/d1a0df13-9a75-4f54-9da1-ef70de55bb6e HTTP/1.1" 200 262 "http://192.168.153.137:8081/ecoe/1/results" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "-"
openecoe_1  | 192.168.153.1 - - [04/Jul/2024:14:57:10 +0000] "GET /backend/api/v1/jobs/d1a0df13-9a75-4f54-9da1-ef70de55bb6e HTTP/1.1" 200 262 "http://192.168.153.137:8081/ecoe/1/results" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "-"
openecoe_1  | 192.168.153.1 - - [04/Jul/2024:14:57:11 +0000] "GET /backend/api/v1/jobs/d1a0df13-9a75-4f54-9da1-ef70de55bb6e HTTP/1.1" 200 262 "http://192.168.153.137:8081/ecoe/1/results" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "-"
openecoe_1  | 192.168.153.1 - - [04/Jul/2024:14:57:12 +0000] "GET /backend/api/v1/jobs/d1a0df13-9a75-4f54-9da1-ef70de55bb6e HTTP/1.1" 200 262 "http://192.168.153.137:8081/ecoe/1/results" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "-"
```
# Inspector browser:
```
main-es2015.0578229….js:1 ERROR 
v
error
: 
Blob {size: 55, type: 'application/json'}
headers
: 
g {normalizedNames: Map(0), lazyUpdate: null, lazyInit: ƒ}
message
: 
"Http failure response for http://192.168.153.137:8081/backend/api/v1/jobs/d1a0df13-9a75-4f54-9da1-ef70de55bb6e/download: 404 NOT FOUND"
name
: 
"HttpErrorResponse"
ok
: 
false
status
: 
404
statusText
: 
"NOT FOUND"
url
: 
"http://192.168.153.137:8081/backend/api/v1/jobs/d1a0df13-9a75-4f54-9da1-ef70de55bb6e/download"
[[Prototype]]
: 



```
Para asegurarme previamente he ejecutado:
sudo docker stop d5226d9225e5 c29adac86c10 d00c1657de64
sudo docker rmi b6ca4388060b 31ebb0b19998 9c893be668ac
sudo rm -rf docker (folder)
git clone --branch develop https://github.com/openECOE/docker.git
sudo docker-compose up
```

**Comment by miguelaf0** [comment]
@sercutos Ya está solucionado, como los cambios del fichero de los resultados están en la rama desarrollo tendrás que cambiar lo siguiente para probarlo: en el archivo `docker-compose.yml`, cambiar el tag de la imagen de `openecoe/one-for-all:latest` a `openecoe/one-for-all:develop`, siendo el resultado final este:

```
...
...
 openecoe:
    build: 
      context: .
      dockerfile: Dockerfile
    image: openecoe/one-for-all:develop
    ports:
      - 8081:80
 ...
 ...
```

**Comment by sercutos** [comment]
Hola.
He borrado todo, descargado el repostorio develop
con :  git clone --branch develop https://github.com/openECOE/docker.git
editado  vim docker-compose.yml
```
  openecoe:
    build:
      context: .
      dockerfile: Dockerfile
    image: openecoe/one-for-all:develop
    ports:
      - 8081:80
```
ejecutado el sudo docker-compose up
ahora ya tengo las imagenes así:

```
openecoe@openecoe2:~/docker$ sudo docker image ls
REPOSITORY             TAG       IMAGE ID       CREATED        SIZE
openecoe/one-for-all   develop   f980e7d55bdd   20 hours ago   833MB
mysql                  latest    31ebb0b19998   3 days ago     586MB
redis                  latest    9c893be668ac   6 weeks ago    116MB
```

pero me sigue dando el mismo error.

**Comment by miguelaf0** [comment]
La imagen de `openecoe/one-for-all` con la tag develop es antigua, la fecha de creación es de hace 20 horas. Prueba a borrarla y descargarla de nuevo:
```
docker pull openecoe/one-for-all:develop
```

**Comment by sercutos** [comment]
Ahora Si, 
Comandos:
```
  sudo docker images
  337  sudo docker rmi -f f980e7d55bdd
  338  sudo docker images
  341  sudo docker pull openecoe/one-for-all:develop
  342  cd docker/
  343  sudo docker images
  345  sudo docker-compose up
```
Logs:
```
Recreating docker_openecoe_1 ... error

ERROR: for docker_openecoe_1  No such image: sha256:f980e7d55bdd12e0444c51824a823a898ba271b83faafbb3c9d53bc09b3a9c38

ERROR: for openecoe  No such image: sha256:f980e7d55bdd12e0444c51824a823a898ba271b83faafbb3c9d53bc09b3a9c38
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]y

```
comprobando Imagenes:

```
openecoe@openecoe2:~/docker$ sudo docker images
REPOSITORY             TAG       IMAGE ID       CREATED          SIZE
openecoe/one-for-all   develop   a708574ea71f   38 minutes ago   834MB
mysql                  latest    31ebb0b19998   3 days ago       586MB
redis                  latest    9c893be668ac   6 weeks ago      116MB
```

Muchas gracias!!!
